# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - imageclassificationrefundbatchprocessing

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # Runs every day at 10 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Create and start virtual environment with dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'imageclassificationrefundbatchprocessing'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./release.zip

      - name: Start Azure Web App with Gunicorn
        run: |
          az webapp config appsettings set --name imageclassificationrefundbatchprocessing --resource-group DLBDSMTP01 --settings GUNICORN_CMD="gunicorn -b 0.0.0.0:8000 app:app"
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Restart Azure Web App
        run: |
          az webapp restart --name imageclassificationrefundbatchprocessing --resource-group DLBDSMTP01
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
